In [ ]:
import pandas_datareader.data as reader
import datetime as dt
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [ ]:
end=dt.date(2020,6,30)
start=dt.date(end.year-5,end.month,end.day)
funds=['FDGRX']

In [ ]:
fundret=reader.get_data_yahoo(funds,start,end)['Adj Close'].pct_change()

In [ ]:
fundmon=fundret.resample('M').agg(lambda x: (x+1).prod()-1)

In [ ]:
fundmon

Symbols        FDGRX
Date
2015-06-30  0.009454
2015-07-31  0.037106
2015-08-31 -0.067351
2015-09-30 -0.040284
2015-10-31  0.083025
...              ...
2020-02-29 -0.044191
2020-03-31 -0.102479
2020-04-30  0.183749
2020-05-31  0.101839
2020-06-30  0.077769

[61 rows x 1 columns]

In [ ]:
factors=reader.DataReader('F-F_Research_Data_Factors','famafrench',start,end)[0]

In [ ]:
factors

         Mkt-RF   SMB    HML    RF
Date
2015-06   -1.53  2.90  -0.79  0.00
2015-07    1.54 -4.19  -4.13  0.00
2015-08   -6.04  0.33   2.77  0.00
2015-09   -3.07 -2.63   0.56  0.00
2015-10    7.75 -1.87  -0.46  0.00
...         ...   ...    ...   ...
2020-02   -8.13  1.07  -3.79  0.12
2020-03  -13.39 -4.88 -13.97  0.13
2020-04   13.65  2.49  -1.23  0.00
2020-05    5.58  2.48  -4.89  0.01
2020-06    2.46  2.70  -2.17  0.01

[61 rows x 4 columns]

In [ ]:
#make the indices of both dataframes same to merge
fundmon.index=factors.index

In [ ]:
fundmon

Symbols     FDGRX
Date
2015-06  0.009454
2015-07  0.037106
2015-08 -0.067351
2015-09 -0.040284
2015-10  0.083025
...           ...
2020-02 -0.044191
2020-03 -0.102479
2020-04  0.183749
2020-05  0.101839
2020-06  0.077769

[61 rows x 1 columns]

In [ ]:
import pandas as pd
merge=pd.merge(fundmon,factors,on='Date')

In [ ]:
merge

            FDGRX  Mkt-RF   SMB    HML    RF
Date
2015-06  0.009454   -1.53  2.90  -0.79  0.00
2015-07  0.037106    1.54 -4.19  -4.13  0.00
2015-08 -0.067351   -6.04  0.33   2.77  0.00
2015-09 -0.040284   -3.07 -2.63   0.56  0.00
2015-10  0.083025    7.75 -1.87  -0.46  0.00
...           ...     ...   ...    ...   ...
2020-02 -0.044191   -8.13  1.07  -3.79  0.12
2020-03 -0.102479  -13.39 -4.88 -13.97  0.13
2020-04  0.183749   13.65  2.49  -1.23  0.00
2020-05  0.101839    5.58  2.48  -4.89  0.01
2020-06  0.077769    2.46  2.70  -2.17  0.01

[61 rows x 5 columns]

In [ ]:
merge[['Mkt-RF','SMB','HML','RF']]=merge[['Mkt-RF','SMB','HML','RF']]/100

In [ ]:
merge

            FDGRX  Mkt-RF     SMB     HML      RF
Date
2015-06  0.009454 -0.0153  0.0290 -0.0079  0.0000
2015-07  0.037106  0.0154 -0.0419 -0.0413  0.0000
2015-08 -0.067351 -0.0604  0.0033  0.0277  0.0000
2015-09 -0.040284 -0.0307 -0.0263  0.0056  0.0000
2015-10  0.083025  0.0775 -0.0187 -0.0046  0.0000
...           ...     ...     ...     ...     ...
2020-02 -0.044191 -0.0813  0.0107 -0.0379  0.0012
2020-03 -0.102479 -0.1339 -0.0488 -0.1397  0.0013
2020-04  0.183749  0.1365  0.0249 -0.0123  0.0000
2020-05  0.101839  0.0558  0.0248 -0.0489  0.0001
2020-06  0.077769  0.0246  0.0270 -0.0217  0.0001

[61 rows x 5 columns]

In [ ]:
merge['FDGRX-RF']=merge.FDGRX-merge.RF

In [ ]:
merge

            FDGRX  Mkt-RF     SMB     HML      RF  FDGRX-RF
Date
2015-06  0.009454 -0.0153  0.0290 -0.0079  0.0000  0.009454
2015-07  0.037106  0.0154 -0.0419 -0.0413  0.0000  0.037106
2015-08 -0.067351 -0.0604  0.0033  0.0277  0.0000 -0.067351
2015-09 -0.040284 -0.0307 -0.0263  0.0056  0.0000 -0.040284
2015-10  0.083025  0.0775 -0.0187 -0.0046  0.0000  0.083025
...           ...     ...     ...     ...     ...       ...
2020-02 -0.044191 -0.0813  0.0107 -0.0379  0.0012 -0.045391
2020-03 -0.102479 -0.1339 -0.0488 -0.1397  0.0013 -0.103779
2020-04  0.183749  0.1365  0.0249 -0.0123  0.0000  0.183749
2020-05  0.101839  0.0558  0.0248 -0.0489  0.0001  0.101739
2020-06  0.077769  0.0246  0.0270 -0.0217  0.0001  0.077669

[61 rows x 6 columns]

In [ ]:
y=merge['FDGRX-RF']
X=merge[['Mkt-RF','SMB','HML']]

X_sm=sm.add_constant(X)

C:\Users\hp\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [ ]:
model=sm.OLS(y,X_sm)

In [ ]:
results=model.fit()

In [ ]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               FDGRX-RF   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.932
Method:                 Least Squares   F-statistic:                     275.2
Date:                Fri, 07 Oct 2022   Prob (F-statistic):           7.27e-34
Time:                        22:27:59   Log-Likelihood:                 175.22
No. Observations:                  61   AIC:                            -342.4
Df Residuals:                      57   BIC:                            -334.0
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0023      0.002      1.182      0.242      -0.002       0.006
Mkt-RF         1.1585      0.045     25.754      0.000       1.068       1.249
SMB            0.2243      0.080      2.792      0.007       0.063       0.385
HML           -0.5033      0.059     -8.586      0.000      -0.621      -0.386
==============================================================================
Omnibus:                        0.061   Durbin-Watson:                   1.835
Prob(Omnibus):                  0.970   Jarque-Bera (JB):                0.042
Skew:                          -0.040   Prob(JB):                        0.979
Kurtosis:                       2.900   Cond. No.                         45.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""